# Generated by Django 4.1.7 on 2023-02-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_from', models.CharField(max_length=65)),
                ('address_to', models.CharField(max_length=65)),
                ('amount', models.IntegerField()),
                ('transaction_hash', models.CharField(max_length=65, null=True)),
            ],
        ),
    ]
